name: Wyoming Whisper API Client
description: Connect to an external whisper.cpp server instance
version: "0.0.13"
slug: wyoming_whisper_api_client
url: https://github.com/stylesuxx/addon-wyoming-whisper-api-client
init: false
startup: services
discovery:
  - wyoming
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  "10300/tcp": null
options:
  debug_logging: true
  api_url: null
schema:
  debug_logging: bool
  api_url: str
